# Generated by Django 3.0.7 on 2020-06-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightearth',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
